### ISSUE TITLE
How to prepare my own firmware 

### ISSUE THREAD

**Issue by KA2010** [cyruscyliu/firmguide-demo#1]
How to prepare my own firmware to use it in your tool, is there any guide help with that.
keep great work.

**Comment by cyruscyliu** [comment]
Sorry for the late reply. Now I am busy with another project, so you might not be able to have our source code in months.

To rehost your own firmware, please tell me the Linux kernel version, architecture, and the SoC model (or related information) of your firmware. I'll try my best to help you.

**Comment by KA2010** [comment]
Thanks for reply, yes I know that your source code is not available yet, Is I can use the docker file to rehost my own firmware?

**Comment by cyruscyliu** [comment]
No, you can't. The docker file contains several rehosted firmware, but cannot be used to rehost firmware.
